import { ClerkProvider } from "@clerk/nextjs";
import { Chivo_Mono } from "next/font/google";

import { cn } from "@/libs/utils";
import AppNav from "@/components/shared/AppNav/AppNav";
import type { Metadata } from "next";

import "./globals.css";
import Provider from "./theme-provider";

const chivoMono = Chivo_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(
            chivoMono.className,
            "bg-primary-white dark:bg-secondary-black text-secondary-black dark:text-primary-white transition-colors duration-200 ease-in-out"
          )}
        >
          <Provider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AppNav />
            <main>{children}</main>
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
